export default {
    active_anc_room_count: "# of Ancillary Rooms",
    active_arch_room_count: "# of Architectural Rooms",
    anc_skup_subtotal: "Ancillary Subtotal",
    anc_skup_total: "Ancillary Total",
    arch_skup_subtotal: "Architectural Subtotal",
    arch_skup_total: "Architectural Total",
    area_phase_date: "Area/Phase Date",
    area_phase_name_id: "Area/Phase Name, ID",
    total_anc_room_count: "Combined # of Ancillary Rooms",
    total_arch_room_count: "Combined # of Architectural Rooms",
    cost_center: "Cost Center (Org)",
    ref_id: "Department ID",
    name: "Department Name",
    department_type: "Department Type",
    division: " Division (Org)",
    inactive_anc_room_count: "Inactive # of Ancillary Rooms",
    inactive_arch_room_count: "Inactive # of Architectural Rooms",
    notes: "Notes",
    redacted_anc_room_count: "Redacted # of Ancillary Rooms",
    redacted_arch_room_count: "Redacted # of Architectural Rooms",
    secondary_information: "Secondary Information",
    state: "State",
};
